### ISSUE TITLE
关闭空调的语音指令写错了

### ISSUE THREAD

**Issue by zhihuaqiu** [dream-inception/butterfly#1]
{COMMANDS_ID_CONDITIONER_OFF, "conditioner_off", {"guan bi kong tiao", "ye deng mo shi"}},
改成
{COMMANDS_ID_CONDITIONER_OFF, "conditioner_off", {"guan bi kong tiao", "guan kong tiao"}},

**Comment by dream-inception** [comment]
非常感谢你的贡献，问题已经修复了
