### ISSUE TITLE
音乐律动模式的眼睛缺少蓝色闪烁

### ISSUE THREAD

**Issue by zhihuaqiu** [dream-inception/butterfly#2]
这两处可以加一下：
eye_switch

    case MODE_LIGHT_BREATH:
            led_ws2812_blink_start(INDICATOR_EYE, INDICATOR_NUM_EYE, 255, 16, 200, 1000);
            break;

eye_blink_start

    case MODE_MUSIC_RHYTHM:
        led_ws2812_blink_start(INDICATOR_EYE, INDICATOR_NUM_EYE, 0, 16, 255, 1000); 
        break;

**Comment by dream-inception** [comment]
非常感谢你的贡献，问题已经修复了
